# Generated by Django 3.2.15 on 2022-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_SKU', models.IntegerField(unique=True)),
                ('brand_name', models.CharField(max_length=127)),
                ('product_slug', models.CharField(max_length=127)),
                ('product_title', models.CharField(max_length=127)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
